# Generated by Django 3.2.4 on 2021-06-26 18:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbrev', models.CharField(max_length=2, unique=True)),
                ('lake_name', models.CharField(max_length=30, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'ordering': ['abbrev'],
            },
        ),
        migrations.CreateModel(
            name='ManagementUnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('abbrev', models.SlugField(blank=True, editable=False, unique=True)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('primary', models.BooleanField(db_index=True, default=False, verbose_name='Primary management unit type for this jurisdiciton.')),
                ('lake', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spatial_mus.lake')),
                ('mu_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='spatial_mus.managementunittype')),
            ],
            options={
                'ordering': ['lake__abbrev', 'mu_type', 'label'],
            },
        ),
        migrations.CreateModel(
            name='FN011',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(db_index=True, max_length=4)),
                ('prj_cd', models.CharField(db_index=True, max_length=13, unique=True)),
                ('slug', models.SlugField(max_length=13, unique=True)),
                ('prj_nm', models.CharField(max_length=255)),
                ('prj_date0', models.DateField()),
                ('prj_date1', models.DateField()),
                ('comment0', models.TextField(blank=True, null=True)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='spatial_mus.lake')),
            ],
            options={
                'ordering': ['-year', '-prj_date1'],
            },
        ),
        migrations.CreateModel(
            name='FN121',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grtp', models.CharField(blank=True, db_index=True, max_length=3, null=True)),
                ('gr', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('sam', models.CharField(db_index=True, max_length=5)),
                ('effdt0', models.DateField(blank=True, db_index=True, null=True)),
                ('effdt1', models.DateField(blank=True, db_index=True, null=True)),
                ('effdur', models.FloatField(blank=True, null=True)),
                ('efftm0', models.TimeField(blank=True, db_index=True, null=True)),
                ('efftm1', models.TimeField(blank=True, db_index=True, null=True)),
                ('effst', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('orient', models.CharField(blank=True, db_index=True, max_length=2, null=True)),
                ('sidep', models.FloatField(blank=True, db_index=True, default=0, null=True)),
                ('secchi', models.FloatField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=100, null=True)),
                ('sitem', models.CharField(blank=True, max_length=5, null=True)),
                ('dd_lat', models.FloatField(blank=True, null=True)),
                ('dd_lon', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text='Represented as (longitude, latitude)', srid=4326)),
                ('comment1', models.CharField(blank=True, max_length=500, null=True)),
                ('management_units', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fn121_samples', to='spatial_mus.managementunit')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='spatial_mus.fn011')),
            ],
            options={
                'ordering': ['project', 'sam'],
                'unique_together': {('project', 'sam')},
            },
        ),
    ]
