# Generated by Django 3.2.4 on 2021-07-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spatial_mus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fn121',
            name='management_units',
        ),
        migrations.AddField(
            model_name='fn121',
            name='management_units',
            field=models.ManyToManyField(blank=True, related_name='fn121_samples', to='spatial_mus.ManagementUnit'),
        ),
        migrations.AlterField(
            model_name='managementunit',
            name='primary',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Primary management unit type for this jurisdiction.'),
        ),
        migrations.AlterField(
            model_name='managementunittype',
            name='label',
            field=models.CharField(max_length=50),
        ),
    ]
